[package]
name = "vpn_health_check"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fateful = "0.1.2"
once_cell = "1.12.0"
tide = "0.16.0"
tokio = { version = "1.19.2", features = ["full"] }
